import type { Metadata } from "next";
import { Josefin_Sans, Sen } from "next/font/google";
import "./globals.css";

export const sen = Sen({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sen",
});

export const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-josefin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sen.variable} ${josefinSans.variable}`}>
      <body
        className={`${sen.className} w-screen min-h-screen m-0 p-0 overflow-x-hidden flex flex-col items-center`}
      >
        {/* <main className="relative mx-auto mb-16 max-w-4xl px-8"> */}
        {children}
        {/* </main> */}
      </body>
    </html>
  );
}
